# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./cmd/agentx/...

builds:
  - id: agentx
    env:
      - CGO_ENABLED=0
    tags:
      - stdjson
    ldflags:
      - -s -w
      - -X github.com/Agentx-network/agentx/cmd/agentx/internal.version={{ .Version }}
      - -X github.com/Agentx-network/agentx/cmd/agentx/internal.gitCommit={{ .ShortCommit }}
      - -X github.com/Agentx-network/agentx/cmd/agentx/internal.buildTime={{ .Date }}
      - -X github.com/Agentx-network/agentx/cmd/agentx/internal.goVersion={{ .Env.GOVERSION }}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - riscv64
      - loong64
      - arm
    goarm:
      - "7"
    main: ./cmd/agentx
    ignore:
      - goos: windows
        goarch: arm

  - id: agentx-desktop
    env:
      - CGO_ENABLED=1
    tags:
      - stdjson
      - webkit2_41
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/agentx-desktop
    binary: agentx-desktop
    hooks:
      pre:
        - cmd: bash -c "cd cmd/agentx-desktop/frontend && npm install && npm run build"
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64

dockers_v2:
  - id: agentx
    dockerfile: docker/Dockerfile.goreleaser
    extra_files:
      - docker/entrypoint.sh
    ids:
      - agentx
    images:
      - "ghcr.io/{{ toLower .Env.GITHUB_REPOSITORY_OWNER }}/agentx"
      - "docker.io/{{ .Env.DOCKERHUB_IMAGE_NAME }}"
    tags:
      - "{{ .Tag }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/riscv64

archives:
  - id: agentx
    builds: [agentx]
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: agentx-desktop
    builds: [agentx-desktop]
    formats: [tar.gz]
    name_template: >-
      agentx-desktop_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - id: agentx
    builds: [agentx]
    package_name: agentx
    file_name_template: >-
      {{ .PackageName }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    vendor: agentx
    homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/agentx
    maintainer: agentx contributors
    description: agentx - a tool for managing and running tasks
    license: MIT
    formats:
      - rpm
      - deb
    bindir: /usr/bin

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# upx:
#    - enabled: true
#      compress: best
#      lzma: true

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - repository:
      owner: Agentx-network
      name: homebrew-tap
    homepage: https://agentx.network
    description: "Autonomous AI agent framework"
    install: |
      bin.install "agentx"
    test: |
      system "#{bin}/agentx", "version"
