// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDefaultBootstrapFiles() {
  return window['go']['main']['AgentSetupService']['CreateDefaultBootstrapFiles']();
}

export function GetBootstrapFiles() {
  return window['go']['main']['AgentSetupService']['GetBootstrapFiles']();
}

export function GetSkillContent(arg1) {
  return window['go']['main']['AgentSetupService']['GetSkillContent'](arg1);
}

export function InstallBuiltinSkills() {
  return window['go']['main']['AgentSetupService']['InstallBuiltinSkills']();
}

export function InstallSkill(arg1) {
  return window['go']['main']['AgentSetupService']['InstallSkill'](arg1);
}

export function ListSkills() {
  return window['go']['main']['AgentSetupService']['ListSkills']();
}

export function RemoveSkill(arg1) {
  return window['go']['main']['AgentSetupService']['RemoveSkill'](arg1);
}

export function SaveBootstrapFile(arg1, arg2) {
  return window['go']['main']['AgentSetupService']['SaveBootstrapFile'](arg1, arg2);
}
