// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDefaultBootstrapFiles():Promise<void>;

export function GetBootstrapFiles():Promise<Array<main.BootstrapFile>>;

export function GetSkillContent(arg1:string):Promise<string>;

export function InstallBuiltinSkills():Promise<void>;

export function InstallFromRegistry(arg1:string):Promise<void>;

export function InstallSkill(arg1:string):Promise<void>;

export function ListSkills():Promise<Array<main.SkillEntry>>;

export function RemoveSkill(arg1:string):Promise<void>;

export function SaveBootstrapFile(arg1:string,arg2:string):Promise<void>;

export function SearchSkills(arg1:string):Promise<Array<main.SkillSearchResult>>;
