// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfigExists():Promise<boolean>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetConfigPath():Promise<string>;

export function GetSetupState():Promise<main.SetupState>;
