// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChatHistory(arg1) {
  return window['go']['main']['ChatService']['GetChatHistory'](arg1);
}

export function IsGatewayReachable() {
  return window['go']['main']['ChatService']['IsGatewayReachable']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['ChatService']['SendMessage'](arg1, arg2);
}
