// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetChatHistory(arg1:string):Promise<Array<main.HistoryMessage>>;

export function IsGatewayReachable():Promise<boolean>;

export function SendMessage(arg1:string,arg2:string):Promise<main.ChatResponse>;
