// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModel(arg1) {
  return window['go']['main']['ConfigService']['AddModel'](arg1);
}

export function GetAgentDefaults() {
  return window['go']['main']['ConfigService']['GetAgentDefaults']();
}

export function GetAvailableProviders() {
  return window['go']['main']['ConfigService']['GetAvailableProviders']();
}

export function GetConfig() {
  return window['go']['main']['ConfigService']['GetConfig']();
}

export function GetImageProviders() {
  return window['go']['main']['ConfigService']['GetImageProviders']();
}

export function GetModelList() {
  return window['go']['main']['ConfigService']['GetModelList']();
}

export function QuickSetupChannel(arg1, arg2) {
  return window['go']['main']['ConfigService']['QuickSetupChannel'](arg1, arg2);
}

export function QuickSetupProvider(arg1, arg2) {
  return window['go']['main']['ConfigService']['QuickSetupProvider'](arg1, arg2);
}

export function RemoveImageProvider(arg1) {
  return window['go']['main']['ConfigService']['RemoveImageProvider'](arg1);
}

export function RemoveModel(arg1) {
  return window['go']['main']['ConfigService']['RemoveModel'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['ConfigService']['SaveConfig'](arg1);
}

export function SetChannelEnabled(arg1, arg2) {
  return window['go']['main']['ConfigService']['SetChannelEnabled'](arg1, arg2);
}

export function SetImageProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ConfigService']['SetImageProvider'](arg1, arg2, arg3, arg4);
}

export function UpdateAgentDefaults(arg1) {
  return window['go']['main']['ConfigService']['UpdateAgentDefaults'](arg1);
}

export function UpdateModel(arg1, arg2) {
  return window['go']['main']['ConfigService']['UpdateModel'](arg1, arg2);
}
