// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {providers} from '../models';

export function AddModel(arg1:config.ModelConfig):Promise<void>;

export function GetAgentDefaults():Promise<config.AgentDefaults>;

export function GetAvailableProviders():Promise<Array<main.ProviderOption>>;

export function GetConfig():Promise<config.Config>;

export function GetImageProviders():Promise<Array<main.ImageProviderInfo>>;

export function GetModelList():Promise<Array<config.ModelConfig>>;

export function ListProviderModels(arg1:string,arg2:string,arg3:string):Promise<Array<providers.DiscoveredModel>>;

export function QuickSetupChannel(arg1:string,arg2:string):Promise<void>;

export function QuickSetupProvider(arg1:string,arg2:string):Promise<void>;

export function RemoveImageProvider(arg1:string):Promise<void>;

export function RemoveModel(arg1:number):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetChannelAllowFrom(arg1:string,arg2:Array<string>):Promise<void>;

export function SetChannelEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetImageProvider(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetupModel(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateAgentDefaults(arg1:config.AgentDefaults):Promise<void>;

export function UpdateModel(arg1:number,arg2:config.ModelConfig):Promise<void>;

export function ValidateProviderKey(arg1:string,arg2:string,arg3:string):Promise<string>;
