// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLogs(arg1:number):Promise<string>;

export function GetStatus():Promise<main.GatewayStatus>;

export function RestartGateway():Promise<void>;

export function StartGateway():Promise<void>;

export function StopGateway():Promise<void>;
