// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogs(arg1) {
  return window['go']['main']['DashboardService']['GetLogs'](arg1);
}

export function GetStatus() {
  return window['go']['main']['DashboardService']['GetStatus']();
}

export function RestartGateway() {
  return window['go']['main']['DashboardService']['RestartGateway']();
}

export function StartGateway() {
  return window['go']['main']['DashboardService']['StartGateway']();
}

export function StopGateway() {
  return window['go']['main']['DashboardService']['StopGateway']();
}
