// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DetectPlatform():Promise<main.PlatformInfo>;

export function FullUninstall():Promise<void>;

export function GetLatestRelease():Promise<string>;

export function HasWallet():Promise<boolean>;

export function InstallBinary():Promise<void>;

export function InstallService():Promise<void>;

export function IsServiceRunning():Promise<boolean>;

export function UninstallService():Promise<void>;
