// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectPlatform() {
  return window['go']['main']['InstallerService']['DetectPlatform']();
}

export function FullUninstall() {
  return window['go']['main']['InstallerService']['FullUninstall']();
}

export function GetLatestRelease() {
  return window['go']['main']['InstallerService']['GetLatestRelease']();
}

export function HasWallet() {
  return window['go']['main']['InstallerService']['HasWallet']();
}

export function InstallBinary() {
  return window['go']['main']['InstallerService']['InstallBinary']();
}

export function InstallService() {
  return window['go']['main']['InstallerService']['InstallService']();
}

export function IsServiceRunning() {
  return window['go']['main']['InstallerService']['IsServiceRunning']();
}

export function UninstallService() {
  return window['go']['main']['InstallerService']['UninstallService']();
}
