// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetRegistration():Promise<main.RegistryInfo>;

export function RegisterAgent(arg1:string,arg2:string):Promise<main.RegistryInfo>;

export function UnregisterAgent():Promise<void>;
