// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRegistration() {
  return window['go']['main']['RegistryService']['GetRegistration']();
}

export function RegisterAgent(arg1, arg2) {
  return window['go']['main']['RegistryService']['RegisterAgent'](arg1, arg2);
}

export function UnregisterAgent() {
  return window['go']['main']['RegistryService']['UnregisterAgent']();
}
