// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListSchedulers():Promise<Array<main.SchedulerInfo>>;

export function RemoveAllSchedulers():Promise<number>;

export function RemoveScheduler(arg1:string):Promise<number>;
