// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListSchedulers() {
  return window['go']['main']['SchedulersService']['ListSchedulers']();
}

export function RemoveAllSchedulers() {
  return window['go']['main']['SchedulersService']['RemoveAllSchedulers']();
}

export function RemoveScheduler(arg1) {
  return window['go']['main']['SchedulersService']['RemoveScheduler'](arg1);
}
