// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToken(arg1, arg2, arg3, arg4) {
  return window['go']['main']['WalletService']['AddToken'](arg1, arg2, arg3, arg4);
}

export function GenerateWallet() {
  return window['go']['main']['WalletService']['GenerateWallet']();
}

export function GetAllBalances() {
  return window['go']['main']['WalletService']['GetAllBalances']();
}

export function GetBalance() {
  return window['go']['main']['WalletService']['GetBalance']();
}

export function GetTokens() {
  return window['go']['main']['WalletService']['GetTokens']();
}

export function GetWallet() {
  return window['go']['main']['WalletService']['GetWallet']();
}

export function RegenerateWallet() {
  return window['go']['main']['WalletService']['RegenerateWallet']();
}

export function RemoveToken(arg1) {
  return window['go']['main']['WalletService']['RemoveToken'](arg1);
}
